input_dataframes:
  - input/mercari-price-suggestion-challenge/train.tsv
  - input/mercari-price-suggestion-challenge/test.tsv
columns:
  - item_description
method: Tfidf
params:
  max_features: 100000
  token_pattern: \w+
  ngram_range: (1, 2)
