name: lgbm
identifier: tuned
model_params:
  objective: binary
  boosting: gbdt
  learning_rate: 0.01
  num_leaves: 31
  reg_alpha: 0.1
  reg_lambda: 0.1
  colsample_bytree: 0.7
  subsample: 0.7
  subsample_freq: 1
  seed: 23974
  tree_learner: serial
  boost_from_average: False
  first_metric_only: True

train_params:
  num_boost_round: 10000
  early_stopping_rounds: 300
  verbose_eval: 100

callbacks:
  - name: log_evaluation
    params:
      logger:
      period: 100

feval: pr_auc
