name: lgbm
identifier: vsb_1st_tuned
model_params:
  objective: binary
  boosting: gbdt
  metric: binary_logloss
  learning_rate: 0.01
  num_leaves: 31
  colsample_bytree: 0.7
  subsample: 0.7
  subsample_freq: 1
  max_depth: 6
  seed: 23974
  boost_from_average: False
  first_metric_only: True

train_params:
  num_boost_round: 10000
  early_stopping_rounds: 100
  verbose_eval: 100

callbacks:
  - name: log_evaluation
    params:
      logger:
      period: 100

feval: pr_auc
