name: lgbm
model_params:
  objective: regression
  boosting: gbdt
  max_depth: -1
  num_leaves: 256
  tree_learner: serial
  learning_rate: 0.01
  colsample_bytree: 0.5
  subsample: 0.7
  subsample_freq: 1
  max_bin: 255
  seed: 71
  feature_fraction_seed: 71
  drop_seed: 71
  verbose: -1
  n_jobs: -1
  first_metric_only: True

train_params:
  num_boost_round: 10000
  early_stopping_rounds: 100
  verbose_eval: 100

callbacks:
  - name: log_evaluation
    params:
      logger:
      period: 100

feval:
