train:
  dir: input/mercari-price-suggestion-challenge
  name: train.tsv
  stats: train.tsv.stats.json
  format: auto
  mode: normal
  structure:
    id_column: train_id
    target: price
  required: all
