input_dataframes:
  - input/atma5/train.csv
  - input/atma5/test.csv
columns:
  - params2
  - spectrum_filename
method: FittingBasedPeakFeatures
params:
  file_dir: input/atma5/spectrum
  diff_span:
    - 1
    - 2
    - 3
    - 4
    - 5
  widths:
    - 0.33
    - 0.5
    - 0.66
    - 0.75
    - 0.8
type: custom.atma5
