input_dataframes:
  - input/atma5/train.csv
  - input/atma5/test.csv
columns:
  - params0
  - params1
  - params2
  - params3
  - params4
  - params5
  - params6
method: FittingCauchy
type: custom.atma5
