input_dataframes:
  - input/atma5/train_spectrum.csv
  - input/atma5/test_spectrum.csv
columns:
  - spectrum_filename
  - wl
  - intensity
method: ParametrizedFWHM
params:
  width:
    - 0.5
    - 0.66
    - 0.75
    - 0.8

type: custom.atma5
