input_dataframes:
  - input/atma5/train.csv
  - input/atma5/test.csv
columns:
  - spectrum_filename
method: BasicOperationsOnSpectrum
params:
  operations:
    - max
  prefix: spectrum

type: custom.atma5
