input_dataframes:
  - input/atma5/train_spectrum.csv
  - input/atma5/test_spectrum.csv
columns:
  - spectrum_filename
  - intensity
method: ReshapeAndScale
params:
  scaling: min_max
type: custom.atma5
