input_dataframes:
  - input/atma5/train_spectrum.csv
  - input/atma5/test_spectrum.csv
columns:
  - spectrum_filename
  - wl
  - intensity
method: SpectrumPeakFeatures
params:
  diff_span:
    - 1
    - 3
    - 5
    - 10
    - 15

type: custom.atma5
