input_dataframes:
  - input/atma5/train_spectrum.csv
  - input/atma5/test_spectrum.csv
columns:
  - spectrum_filename
  - wl
  - intensity
method: WindowedMeanMax
params:
  window_size:
    - 3
    - 5
    - 7
    - 10
    - 15

type: custom.atma5
