features:
  - name: SpectrumPeakFeatures
    path: Atma5_13_SpectrumPeakFeatures_train.ftr
    role: train
  - name: SpectrumPeakFeatures
    path: Atma5_13_SpectrumPeakFeatures_test.ftr
    role: test
