features:
  - name: SpecStdSkewKurt
    path: Atma5_13_SpecStdSkewKurt_spectrum_filename_train.ftr
    role: train
  - name: SpecStdSkewKurt
    path: Atma5_13_SpecStdSkewKurt_spectrum_filename_test.ftr
    role: test
