feature_dir: features/

output_dir: output/

log_dir: log

callbacks:
  - name: FeatureSavingCallback
    type: features
    params:
      prefix: Atma5
  - name: ConcatenateFeatureCallback
    type: features
  - name: MergeFittingCallback
    type: custom.atma5

pipeline:
  - data_loading:
      - configs/data_loading/atma5/train.yml
      - configs/data_loading/atma5/fitting.yml
      - configs/data_loading/atma5/test.yml
  - features:
      - configs/features/atma5/label_encodes.yml
      - configs/features/atma5/apply_nothing.yml
      - configs/features/atma5/spectrum_basic_op.yml
