feature_dir: features/

output_dir: output/

log_dir: log

callbacks:
  - name: ConcatenateFeatureCallback
    type: features

  - name: FeatureSavingCallback
    type: features
    params:
      prefix: Atma5_22

  - name: OOFAPCallback
    type: model

  - name: OOFAUCCallback
    type: model
    group: av

  - name: CreateSubmissionCallback
    type: custom.atma5
    params:
      save_dir:
      prefix: submission

  - name: PrepareForStratifiedKFoldCallback
    type: split

  - name: FoldAUCCallback
    type: train_fold
    group: av

  - name: FoldAPCallback
    type: train_fold

  - name: OutputResultsCallback
    type: model

pipeline:
  - feature_loading:
      - configs/feature_loading/atma5/spectrum_raw_21.yml
  - av: configs/adversarial/atma5/av_with_nn.yml
  - split: configs/split/stratified_kfold.yml
  - model: configs/model/atma5/conv1d_binary.yml
  - prediction: configs/prediction/atma5/to_submission.yml
