feature_dir: features/

output_dir: output/

log_dir: log

pipeline:
  - data_loading:
      - configs/data_loading/mercari/train_sample.yml
      - configs/data_loading/mercari/test_sample.yml
    features:
    preprocess:
    av: configs/adversarial/av_with_lgbm.yml
    split: configs/split/kfold.yml
    model: configs/model/lgbm_regression.yml
