feature_dir: features/

output_dir: output/

log_dir: log

callbacks:
  - name: FeatureSavingCallback
    type: features
  - name: ConcatenateFeatureCallback
    type: features
  - name: FillNACallback
    type: custom
    params:
      columns:
        - item_description
      values:
        item_description: ""

pipeline:
  - data_loading:
      - configs/data_loading/mercari/train_sample.yml
      - configs/data_loading/mercari/test_sample.yml
    features:
      - configs/features/mercari/tfidf_on_description.yml
      - configs/features/mercari/target_encode_item_condition_id.yml
    split: configs/split/kfold.yml
    model: configs/model/lgbm_regression.yml
